spring:
  application:
    name: ad-auction-service
  redis:
    host: localhost
    port: 6379
    timeout: 2000ms

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,metrics
  metrics:
    export:
      simple:
        enabled: true

logging:
  level:
    com.adauction: INFO